// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqfyndqxefbusitozwoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxZnluZHF4ZWZidXNpdG96d29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTgyMzgsImV4cCI6MjA2MDI3NDIzOH0.b9Styi1minksr51YvggBmiddEs1XoFXVgWe1PsKJb3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);